import pygame
pygame.font.init()

WIDTH, HEIGHT = 1800, 900

FPS = 150

IDLE_COLOR = "white"
SORTED_COLOR = "lightblue"

SORTING_COLOR1 = "red"
SORTING_COLOR2 = "yellow"
PIVOT_COLOR = "green"

BACKGROUND_COLOR = "black"

SORT_TOP = HEIGHT * .1
SORT_BOTTOM_PAD = HEIGHT * .03
SORT_BOTTOM = HEIGHT - SORT_BOTTOM_PAD
SORT_MAX_HEIGHT = HEIGHT - SORT_TOP - SORT_BOTTOM_PAD
X_PADDING = 20  # Needs to be integer

UI_TOP = HEIGHT * .01
TEXT_BOX_HEIGHT = HEIGHT * .02
FONT_SIZE = int(HEIGHT * .02)

FPS_TUPLE = (X_PADDING, UI_TOP)
COUNT_TUPLE = (X_PADDING, UI_TOP + TEXT_BOX_HEIGHT)
ALGO_TUPLE = (X_PADDING, UI_TOP + 2 * TEXT_BOX_HEIGHT)
TIME_TUPLE = (X_PADDING, UI_TOP + 3 * TEXT_BOX_HEIGHT)
ENTRY_RECT = (WIDTH * .35, HEIGHT * .05, WIDTH * .3, HEIGHT * .05)

my_font = pygame.font.SysFont('Century Schoolbook', FONT_SIZE)
